Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-04, with the labels that each got.

#1756 Support provisioning by external id
  cmd/svcat/output/instance.go
  pkg/apis/servicecatalog/plan_reference.go
  pkg/apis/servicecatalog/plan_reference_test.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/plan_reference.go
  pkg/apis/servicecatalog/v1beta1/plan_reference_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/controller/controller.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/servicecatalog/instance/strategy.go
  pkg/registry/servicecatalog/instance/strategy_test.go
  plugin/pkg/admission/serviceplan/changevalidator/admission.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#1846 Bash completion for svcat
  cmd/svcat/completion/completion_cmd.go
  cmd/svcat/main.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL, svcat

#1261 e2e explicit plan check
  test/e2e/broker.go
  test/e2e/walkthrough.go
  test/util/util.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1915 Wait for caches to sync before starting up the controller (fixes #1907)
  cmd/controller-manager/app/controller_manager.go
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/XS

#1919 fix v0.1.13 strings
  charts/catalog/Chart.yaml
  pkg/features/features.go
Labels: cncf-cla: yes, size/XS

#1910 Move serviceClass references to clusterServiceClass in controllers
  pkg/controller/controller.go
  pkg/controller/controller_broker.go
  pkg/controller/controller_clusterserviceclass.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1925 Update to osb client 0.0.10
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
Labels: LGTM1, cncf-cla: yes, size/M

#1909 Move servicePlan references to clusterServicePlan in controllers
  pkg/controller/controller.go
  pkg/controller/controller_broker.go
  pkg/controller/controller_clusterserviceplan.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1918 Disambiguate controller test consts
  pkg/apis/servicecatalog/validation/broker_test.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_broker_test.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/registry/servicecatalog/instance/strategy_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1917 Add feature flag for making instance/binding locks optional
  pkg/apis/servicecatalog/validation/binding.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/features/features.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1929 prevent artificial delays due to ridiculously low client attempts
  test/e2e/framework/framework.go
  test/integration/controller_instance_test.go
  test/integration/framework.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1937 make docs right
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1951 SLEEP! Fix an integration test.
  pkg/controller/controller.go
  test/integration/controller_binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1953 The ups broker should log to stderr instead of to files only
  charts/ups-broker/templates/broker-deployment.yaml
  charts/ups-broker/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1952 Fix "Starting server" log message in ups broker
  contrib/pkg/broker/server/server.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1927 Additional SecretTransforms in ServiceBinding (add key w/ JSONPath template, remove key, merge another secret)
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
  pkg/controller/serializer.go
  pkg/controller/serializer_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_binding_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1887 Add tests and fix controller so it never mutates input
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_broker_test.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1931 Wait for caches to sync before starting up the controller
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1944 Add JSON and YAML output to svcat
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/broker/get_cmd.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/command/command.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/output/binding.go
  cmd/svcat/output/broker.go
  cmd/svcat/output/class.go
  cmd/svcat/output/instance.go
  cmd/svcat/output/json.go
  cmd/svcat/output/output.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/get-binding.json
  cmd/svcat/testdata/output/get-binding.yaml
  cmd/svcat/testdata/output/get-bindings.json
  cmd/svcat/testdata/output/get-bindings.yaml
  cmd/svcat/testdata/output/get-broker.json
  cmd/svcat/testdata/output/get-broker.yaml
  cmd/svcat/testdata/output/get-brokers.json
  cmd/svcat/testdata/output/get-brokers.yaml
  cmd/svcat/testdata/output/get-class.json
  cmd/svcat/testdata/output/get-class.yaml
  cmd/svcat/testdata/output/get-classes.json
  cmd/svcat/testdata/output/get-classes.yaml
  cmd/svcat/testdata/output/get-instance.json
  cmd/svcat/testdata/output/get-instance.yaml
  cmd/svcat/testdata/output/get-instances.json
  cmd/svcat/testdata/output/get-instances.yaml
  cmd/svcat/testdata/output/get-plan.json
  cmd/svcat/testdata/output/get-plan.yaml
  cmd/svcat/testdata/output/get-plans.json
  cmd/svcat/testdata/output/get-plans.yaml
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#1957 Rename ServiceBinding.spec.secretTransform to secretTransforms (plural)
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
  pkg/openapi/openapi_generated.go
  test/integration/controller_binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1975 Workaround golint hosting problem
  build/build-image/Dockerfile
Labels: LGTM1, cncf-cla: yes, size/XS

#1955 Consolidate svcat plugin logic
  cmd/svcat/main.go
  cmd/svcat/plugin/plugin.go
  cmd/svcat/svcat_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1974 add rbac rules for cluster-info
  charts/catalog/templates/rbac.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1979 Fixed fetch message for broker synchronization
  cmd/svcat/broker/sync_cmd.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1904 Service Catalog health check tool
  Makefile
  charts/healthcheck/Chart.yaml
  charts/healthcheck/README.md
  charts/healthcheck/templates/_helpers.tpl
  charts/healthcheck/templates/healthcheck-deployment.yaml
  charts/healthcheck/templates/healthcheck-service.yaml
  charts/healthcheck/templates/rbac.yaml
  charts/healthcheck/templates/serviceaccounts.yaml
  charts/healthcheck/values.yaml
  cmd/healthcheck/framework/healthcheck.go
  cmd/healthcheck/framework/http.go
  cmd/healthcheck/framework/metrics.go
  cmd/healthcheck/framework/options.go
  cmd/healthcheck/framework/utils.go
  cmd/healthcheck/main.go
  contrib/build/healthcheck/Dockerfile
  contrib/examples/prometheus/prometheus.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#1981 Fix event recorder scheme
  cmd/controller-manager/app/controller_manager.go
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/S

#1984 fix hyperkube to run from goland.
  cmd/service-catalog/main.go
  cmd/service-catalog/server/apiserver.go
  cmd/service-catalog/server/controller-manager.go
  pkg/hyperkube/hyperkube.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1930 svcat: bind and provision now support optional --external-id
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1992 Update references to unsupported k8s versions
  docs/devguide.md
  docs/install.md
  docs/introduction.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1999 update chart references to v0.1.16
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#1994 Float docs TOC navbar when scrolling
  docsite/_sass/_base.sass
  docsite/_sass/_desktop.sass
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1916 Keep InProgressProperties up-to-date
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, non-happy-path, size/L

#2004 Fix broken links on doc site
  docs/design.md
  docsite/index.html
Labels: LGTM1, cncf-cla: yes, size/S

#1988 Ensure a Namespaced KeyFunc for ServicePlans
  contrib/examples/apiserver/serviceplan.yaml
  pkg/registry/servicecatalog/serviceplan/storage.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1972 Only validate status on updates
  pkg/apis/servicecatalog/validation/binding.go
  pkg/apis/servicecatalog/validation/binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1911 Move serviceBroker references to clusterServiceBroker in controllers
  contrib/examples/prometheus/README.md
  pkg/controller/controller.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, needs-rebase, size/M
