Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-11, with the labels that each got.

#2457 Fix typos: verfies -> verifies
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2458 Fix typos: correcness -> correctness
  pkg/controller/serializer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2459 delete redundant symbol
  docsite/css/blog.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2453 Update svcat docs
  docs/cli.md
  docsite/_data/cli.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2462 Fix typos in comment
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2464 Log ServiceInstance ADDED & UPDATED events
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2465 Fix typos: specifc->specific classses->classes
  cmd/svcat/extra/marketplace_cmd.go
  pkg/apiserver/default_storage_factory_builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2468 Refactor svcat uuid flags to kube-name
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/class/testdata/describe-class.txt
  cmd/svcat/output/class.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/plan/describe_cmd_test.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/describe-class.txt
  cmd/svcat/testdata/output/describe-namespace-plan.txt
  cmd/svcat/testdata/output/describe-plan-with-schemas.txt
  cmd/svcat/testdata/output/describe-plan-without-schemas.txt
  cmd/svcat/testdata/output/describe-plan.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/plan_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2470 Fix typos: sucessfully->successfully, variuos->various
  pkg/apiserver/etcd_config.go
  pkg/svcat/service-catalog/sdk.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2472 Bump release v0.1.38
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2471 Add RetrievePlanByClassIDAndName to pkg/svcat
  cmd/svcat/instance/provision_cmd.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
  pkg/svcat/service-catalog/options.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/plan_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2474 Fix spell error: condiiton -> condition
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2473 Don't fail DELETE if instance was not provisioned due to terminal failure
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2475 Fix defaultserviceplan comment problem
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2463 Add namespace-scoped example of UPS Broker
  contrib/examples/walkthrough/ups-clusterservicebroker.yaml
  contrib/examples/walkthrough/ups-servicebroker.yaml
  contrib/jenkins/test_walkthrough.sh
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2484 fix a typo
  plugin/pkg/admission/serviceplan/changevalidator/admission_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2460 Rename extras to browsing
  cmd/svcat/browsing/browsing_suite_test.go
  cmd/svcat/browsing/marketplace_cmd.go
  cmd/svcat/browsing/marketplace_cmd_test.go
  cmd/svcat/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2485 fix using nil error problem
  plugin/pkg/admission/servicebindings/lifecycle/admission_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2476 Fix NewFor to GetRESTOptions
  pkg/apiserver/etcd_rest_options_factory.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2483 delete some code
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2489 fix func name comment problem
  pkg/controller/controller_clusterservicebroker_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2455 Simplify & improve performance of PrettyContextBuilder
  pkg/pretty/context_builder.go
  pkg/pretty/context_builder_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2499 Fix typo: verison -> version
  charts/catalog/templates/_helpers.tpl
  charts/healthcheck/templates/_helpers.tpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2498 fix TestResponseWriterGetResponse problem
  pkg/rest/core/fake/rest_client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2496 fix func comment problem
  pkg/controller/controller_clusterservicebroker_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2491 On startup, wait longer for Catalog resources to be available from API Server
  cmd/controller-manager/app/controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2497 fix func name comment problem
  pkg/controller/controller_instance_ns_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2507 Remove excess code.
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
