Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-02, with the labels that each got.

#1733 Disable test-dep target temporarily
  Makefile
Labels: LGTM1, cncf-cla: yes, size/XS

#1731 allow setting go version, clean up alignment
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1696 remove last vestiges of glide
  Makefile
  build/build-image/Dockerfile
  contrib/jenkins/init_build.sh
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1729 phony output binaries
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1708 handle instance deletion that occurs during async provisioning or async update (#1587)
  pkg/controller/controller_instance.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1741 chart changes for v0.1.8
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#1730 Added validation for ServiceBinding spec ParametersFrom
  pkg/apis/servicecatalog/validation/binding.go
  pkg/apis/servicecatalog/validation/binding_test.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/validation/validation.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1732 Add a constraint on go-autorest
  Gopkg.lock
  Gopkg.toml
  pkg/svcat/dep.go
  test/test-dep.sh
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1668 Allow upper case letters in Plan names
  pkg/apis/servicecatalog/validation/serviceclass.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/validation/serviceplan.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1735 wrap "rm -rf" with docker
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1745 Increase timeout for broker condition polling in e2e
  test/e2e/broker.go
  test/e2e/util.go
  test/e2e/walkthrough.go
  test/util/util.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1738 Add constraint for go-open-service-broker-client
  Gopkg.lock
  Gopkg.toml
  docs/devguide.md
  vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, needs-rebase, size/L

#1740 print schemas when describing plan in svcat
  cmd/svcat/output/plan.go
  cmd/svcat/output/yaml.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/describe-plan-with-schemas.txt
  cmd/svcat/testdata/output/describe-plan-without-schemas.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/clusterserviceplans.json
  cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
  cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.externalName=premium.json
  cmd/svcat/testdata/responses/serviceinstances?fieldSelector=spec.clusterServicePlanRef.name=cc0d7529-18e8-416d-8946-6f7456acd589.json
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1743 allow getting and describing plans with class/plan name combo in svcat
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/responses/clusterserviceplans?fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  pkg/svcat/service-catalog/plan.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1746 log the version and build date on server startup
  pkg/hyperkube/hyperkube.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1693 Ensure only href-checker runs on docs only commit
  .travis.yml
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1684 use pvc for etcd volume
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/etcd-pvc.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1734 also build with golang tip and allow tip to fail
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1725 Publish svcat binaries during build
  .travis.yml
  Makefile
  build/build-image/Dockerfile
  cmd/svcat/README.md
  cmd/svcat/main.go
  contrib/travis/deploy.sh
  docs/devguide.md
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/L

#1759 fix indentation from #1725
  .travis.yml
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/XS

#1750 In svcat verify service instance exists on unbind (#1744)
  pkg/svcat/service-catalog/binding.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1719 Add unit tests for binding and broker backends in svcat
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service_catalog_suite_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1764 2 of 4 fixes for golang 1.10
  pkg/apis/settings/v1alpha1/types.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1760 handle binding deletion that occurs during async bind
  pkg/controller/controller_binding.go
  test/integration/controller_binding_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1768 Bump dependency on go-open-service-broker-client to 0.0.3
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/constants.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1770 Reset RemovedFromBrokerCatalog when broker re-adds a removed service class
  pkg/controller/controller_broker.go
  pkg/controller/controller_broker_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M
