Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-08, with the labels that each got.

#2226 Make the last col of get-classes and get-plans wider so we're at least 80 cols
  cmd/svcat/output/class.go
  cmd/svcat/output/plan.go
  cmd/svcat/output/table.go
  cmd/svcat/testdata/output/get-plans.json
  cmd/svcat/testdata/output/get-plans.txt
  cmd/svcat/testdata/output/get-plans.yaml
  cmd/svcat/testdata/responses/catalog/clusterserviceplans.json
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2248 Enable namespaced brokers by default
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
  docs/namespaced-broker-resources.md
  pkg/features/features.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/S

#1966 Add some dependency logic around generators.
  Makefile
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/M

#2256 v0.1.28 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2258 Replace forked KubernetesNamespaceLifecycle admission plugin with k8s.io/apiserver one
  charts/catalog/templates/apiserver-deployment.yaml
  cmd/apiserver/app/server/plugins.go
  plugin/pkg/admission/namespace/lifecycle/admission.go
  plugin/pkg/admission/namespace/lifecycle/admission_test.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2259 Fix panic when retry duration is exceeded
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/S

#2263 Fix catalog chart rbac to use new namespacedServiceBrokerDisabled flag
  charts/catalog/templates/rbac.yaml
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2265 Remove unused function
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2214 Ensure that ObjectMeta field selectors (e.g. name and namespace) can be used appropriately for all types
  pkg/apis/servicecatalog/v1beta1/conversion.go
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/clusterservicebroker/storage.go
  pkg/registry/servicecatalog/clusterserviceclass/storage.go
  pkg/registry/servicecatalog/clusterserviceplan/storage.go
  pkg/registry/servicecatalog/instance/storage.go
  pkg/registry/servicecatalog/servicebroker/storage.go
  test/integration/clientset_test.go
  test/integration/util.go
Labels: LGTM1, approved, cncf-cla: yes, lgtm, size/XL

#2262 Add a DashboardURL row to svcat describe instances
  cmd/svcat/output/instance.go
  cmd/svcat/output/instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2275 release v 0.1.29
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2272 Enable setting tls communication with etcd in helm chart
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2273 Add homebrew install docs for svcat
  docs/install.md
Labels: LGTM1, approved, cncf-cla: yes, lgtm, size/XS

#2271 Remove hardcoded Etcd image and pull policy
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2091 Improve kubectl get experience for service catalog resources
  Gopkg.lock
  Gopkg.toml
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/clusterservicebroker/storage.go
  pkg/registry/servicecatalog/clusterserviceclass/storage.go
  pkg/registry/servicecatalog/clusterserviceplan/storage.go
  pkg/registry/servicecatalog/instance/storage.go
  pkg/registry/servicecatalog/servicebroker/storage.go
  pkg/registry/servicecatalog/serviceclass/storage.go
  pkg/registry/servicecatalog/serviceplan/storage.go
  pkg/registry/servicecatalog/tableconvertor/tableconvertor.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
Labels: approved, awaiting-ci, cncf-cla: yes, lgtm, size/L

#2208 Add flags to svcat register broker command
  cmd/svcat/broker/register_cmd.go
  cmd/svcat/broker/register_cmd_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/assets/ca
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/options.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2280 Use instance UID instead of name in broker op backoff/retry
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2277 Make Originating Identity feature gate on by default
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
  docs/devguide.md
  docs/feature-gates.md
  docsite/_data/devguide.yaml
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_instance_test.go
  pkg/features/features.go
  pkg/registry/servicecatalog/binding/strategy_test.go
  pkg/registry/servicecatalog/clusterservicebroker/strategy_test.go
  pkg/registry/servicecatalog/instance/strategy_test.go
  pkg/registry/servicecatalog/servicebroker/strategy_test.go
  test/integration/controller_test.go
  test/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2287 Add Context object to Bind requests (OSBAPI)
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_ns_test.go
  pkg/controller/controller_binding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2286 cleanup event message for broker retry
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2303 Remove regex validation of service class external IDs
  pkg/apis/servicecatalog/validation/serviceclass.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2296 Fix validation error's bad value (ServicePlan instead of ServiceClass)
  pkg/apis/servicecatalog/validation/broker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2311 Reject ServiceBrokers whose catalogRestrictions reference invalid fields
  pkg/apis/servicecatalog/v1beta1/filter.go
  pkg/apis/servicecatalog/validation/broker.go
  pkg/apis/servicecatalog/validation/broker_test.go
  pkg/filter/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2300 Fix field order in CatalogRestriction in servicecatalog/types.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2304 support for headless services for API server
  charts/catalog/README.md
  charts/catalog/templates/apiserver-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
