Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-03, with the labels that each got.

#1775 Bump dependency on go-open-service-broker-client to 0.0.4
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1774 prometheus: only return catalog specific metrics
  pkg/metrics/metrics.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1763 Add unit tests for class, instance, plan backends in svcat
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/instance_test.go
  pkg/svcat/service-catalog/plan_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1776 chart changes for v0.1.9
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#1777 Fix svcat cli publish
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1782 Add all-namespaces flag to svcat
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/get-bindings-all-namespaces.txt
  cmd/svcat/testdata/output/get-instances-all-namespaces.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/namespaces/default/servicebindings.json
  cmd/svcat/testdata/responses/namespaces/default/servicebindings/ups-binding.json
  cmd/svcat/testdata/responses/namespaces/default/serviceinstances.json
  cmd/svcat/testdata/responses/namespaces/default/serviceinstances/ups-instance.json
  cmd/svcat/testdata/responses/namespaces/test-ns/serviceinstances/ups-binding.json
  cmd/svcat/testdata/responses/servicebindings.json
  cmd/svcat/testdata/responses/serviceinstances.json
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1780 Add carolynvs to OWNERS
  OWNERS
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1748 Add ObservedGeneration and Provisioned into ServiceInstanceStatus
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  test/integration/clientset_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
  test/util/util.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1781 allow brokers to respond to getCatalog() with no services (#1772)
  pkg/controller/controller_broker.go
  pkg/controller/controller_broker_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1788 Remove Failed condition if there was no terminal failure
  pkg/controller/controller_instance.go
Labels: cncf-cla: yes, size/M

#1762 Adding the ability to sync a service instance
  cmd/svcat/main.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/touch/touch_cmd.go
  cmd/svcat/touch/touch_instance_cmd.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1799 Print deleted bindings
  cmd/svcat/README.md
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/output/binding.go
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1785 Add enhanced parameter options to provision
  cmd/svcat/README.md
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/parameters/parameters.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/parameters.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M, svcat

#1751 Allow retries for instances with Failed condition after spec changes
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  test/integration/framework.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1809 Export the touch instance command
  cmd/svcat/instance/touch_cmd.go
  cmd/svcat/main.go
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/touch/touch_cmd.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1779 Controller reconciliation rework - part 1 (ServiceInstance)
  pkg/controller/controller_actions_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1813 Fix failing test: TestReconcileServiceInstanceWithFailedCondition
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1801 Synchronize some generated code that was missed along the way
  pkg/openapi/openapi_generated.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1784 Integrate svcat docs with Service Catalog's
  docs/README.md
  docs/cli.md
  docs/install.md
  docs/walkthrough.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1819 Controller reconciliation rework - part 2 (ServiceBinding)
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1823 Update catalog charts README configuration
  charts/catalog/README.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1806 Add behavior to print deleted instance name
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/output/binding.go
  cmd/svcat/output/output.go
  docs/cli.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1824 reset RemovedFromBroker flag on plans that are re-added by broker
  pkg/controller/controller_broker.go
  pkg/controller/controller_broker_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1803 Pass correct plan ID in deprovision request (for both deleting and orphan mitigation)
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, non-happy-path, size/L

#1838 A new test was added after pre-checks happened for last pr.
  pkg/svcat/service-catalog/plan_test.go
Labels: cncf-cla: yes, size/XS

#1836 Use k8s NewUUID method exclusively
  Gopkg.lock
  contrib/pkg/brokerapi/fake/fake.go
  pkg/apis/servicecatalog/testing/fuzzer.go
  pkg/apis/servicecatalog/unstructured_test.go
  pkg/apis/servicecatalog/v1beta1/defaults.go
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/uuid.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1833 Extracting common plan spec into embeddable struct
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/pretty/pretty_names_test.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
  test/integration/clientset_test.go
  test/integration/controller_instance_test.go
  test/integration/deleted_services_and_plans_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1840 gitignore integration.test binary
  .gitignore
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1843 Revert "Pass correct plan ID in deprovision request (for both deletin…
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, cncf-cla: yes, size/L

#1845 disable tests for Deploy stage in Travis
  .travis.yml
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/XS

#1847 [WIP] Pass correct plan ID in deprovision request (for both deleting and orphan mitigation)
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  test/integration/controller_binding_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
Labels: cncf-cla: yes, size/L

#1849 Support for OSB PR #452 to allow periods in the name field
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/validation/serviceclass.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/validation/serviceplan.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1834 Extract common service class spec fields
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/pretty/pretty_names_test.go
  plugin/pkg/admission/serviceplan/changevalidator/admission_test.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
  test/integration/clientset_test.go
  test/integration/controller_instance_test.go
  test/integration/deleted_services_and_plans_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1841 Extracting common broker spec elements into embeddable struct
  contrib/pkg/brokerapi/openservicebroker/open_service_broker_client_test.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/broker_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_broker_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/servicecatalog/broker/strategy_test.go
  plugin/pkg/admission/broker/authsarcheck/admission_test.go
  test/e2e/broker.go
  test/e2e/walkthrough.go
  test/integration/clientset_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1789 OrphanMitigation condition and different handling of retry timeout
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, non-happy-path, size/L

#1844 pick a better random port to listen on in integration tests
  test/integration/framework.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1850 Rename SharedServicePlanSpec to CommonServicePlanSpec
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/pretty/pretty_names_test.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
  test/integration/clientset_test.go
  test/integration/controller_instance_test.go
  test/integration/deleted_services_and_plans_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1856 Bump dependency on go-open-service-broker-client to 0.0.6
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/constants.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1852 Update registry code from serviceclass to clusterserviceclass
  pkg/registry/servicecatalog/clusterserviceclass/storage.go
  pkg/registry/servicecatalog/clusterserviceclass/storage_test.go
  pkg/registry/servicecatalog/clusterserviceclass/strategy.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog.go
  pkg/registry/servicecatalog/serviceclass/strategy.go
Labels: LGTM1, LGTM2, LGTM3, cncf-cla: yes, size/L

#1832 fix async deprovision retry
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  test/integration/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1862 Fix NamespaceScoped doc text for ns resources
  pkg/registry/servicecatalog/binding/strategy.go
  pkg/registry/servicecatalog/instance/strategy.go
Labels: cncf-cla: yes, size/XS

#1863 Add NamespacedServiceBroker Feature Gate
  pkg/features/features.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1864 Add NamespacedServiceBroker feature gate to helm chart
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1865 Refactor common broker validations
  pkg/apis/servicecatalog/validation/broker.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1858 Refactor common serviceclass validations
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/serviceclass.go
  pkg/apis/servicecatalog/validation/serviceplan.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1855 clear polling queue when starting new operation
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#1866 v0.1.10 release changes
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#1839 add svcat version
  cmd/svcat/main.go
  cmd/svcat/output/version.go
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/versions/version_cmd.go
  docs/install.md
  pkg/svcat/service-catalog/version.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1870 Refactor service plan validations to extract common logic
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/serviceplan.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1765 4xx, 5xx and Connection timeout should be retriable (not terminal errors)
  Jenkinsfile
  pkg/controller/controller.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, non-happy-path, size/XL

#1869 Support OSB API response schemas
  Gopkg.lock
  Gopkg.toml
  contrib/pkg/broker/user_provided/controller/controller.go
  contrib/pkg/brokerapi/schemas.go
  pkg/apis/servicecatalog/testing/fuzzer.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1802 Use namesapce from current context in standalone svcat binary
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/broker/describe_cmd.go
  cmd/svcat/command/command.go
  cmd/svcat/command/namespaced.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/describe_cmd.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/instance/touch_cmd.go
  cmd/svcat/main.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/kubeconfig.tmpl.yaml
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/kube/kube.go
  pkg/svcat/svcat.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1860 Display parameters in svcat describe instance/binding output
  cmd/svcat/output/binding.go
  cmd/svcat/output/instance.go
  cmd/svcat/output/yaml.go
  cmd/svcat/testdata/output/describe-binding.txt
  cmd/svcat/testdata/output/describe-instance.txt
  cmd/svcat/testdata/responses/namespaces/test-ns/servicebindings/ups-binding.json
  cmd/svcat/testdata/responses/namespaces/test-ns/serviceinstances/ups-binding.json
  cmd/svcat/testdata/responses/namespaces/test-ns/serviceinstances/ups-instance.json
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1254 statically compile
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1875 update debian base from jessie to stretch
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1882 Fix common validations regression
  pkg/apis/servicecatalog/validation/broker.go
  pkg/apis/servicecatalog/validation/serviceclass.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1658 Cluster-id configmap
  cmd/controller-manager/app/controller_manager.go
  cmd/controller-manager/app/options/options.go
  pkg/apis/componentconfig/types.go
  pkg/controller/controller.go
  pkg/controller/controller_clusterid_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XL

#1878 Update of name in example ServiceClass
  docs/resources.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1886 Orphan mitigation for async provisioning
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#1883 Rename/move existing "ServicePlan" things
  contrib/examples/apiserver/clusterserviceplan.yaml
  contrib/hack/test-apiserver.sh
  pkg/registry/servicecatalog/clusterserviceplan/storage.go
  pkg/registry/servicecatalog/clusterserviceplan/strategy.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1868 Credentials remapping
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
  pkg/openapi/openapi_generated.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1880 Update registry code from broker to clusterservicebroker
  pkg/openapi/openapi_generated.go
  pkg/registry/servicecatalog/clusterservicebroker/storage.go
  pkg/registry/servicecatalog/clusterservicebroker/storage_test.go
  pkg/registry/servicecatalog/clusterservicebroker/strategy.go
  pkg/registry/servicecatalog/clusterservicebroker/strategy_test.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1893 v0.1.12 release changes
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#1889 Svcat bind params now supports --params-json
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/binding.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L, svcat

#1894 Adding ServicePlan (namespaced plans) API
  contrib/examples/apiserver/clusterserviceplan.yaml
  contrib/examples/apiserver/serviceplan.yaml
  contrib/hack/test-apiserver.sh
  pkg/apis/servicecatalog/register.go
  pkg/apis/servicecatalog/testing/fuzzer.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/conversion.go
  pkg/apis/servicecatalog/v1beta1/conversion_test.go
  pkg/apis/servicecatalog/v1beta1/register.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/serviceplan.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_servicecatalog_client.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_serviceplan.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/servicecatalog_client.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/serviceplan.go
  pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_servicecatalog_client.go
  pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/fake/fake_serviceplan.go
  pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/generated_expansion.go
  pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/servicecatalog_client.go
  pkg/client/clientset_generated/internalclientset/typed/servicecatalog/internalversion/serviceplan.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/servicecatalog/v1beta1/interface.go
  pkg/client/informers_generated/externalversions/servicecatalog/v1beta1/serviceplan.go
  pkg/client/informers_generated/internalversion/generic.go
  pkg/client/informers_generated/internalversion/servicecatalog/internalversion/interface.go
  pkg/client/informers_generated/internalversion/servicecatalog/internalversion/serviceplan.go
  pkg/client/listers_generated/servicecatalog/internalversion/expansion_generated.go
  pkg/client/listers_generated/servicecatalog/internalversion/serviceplan.go
  pkg/client/listers_generated/servicecatalog/v1beta1/expansion_generated.go
  pkg/client/listers_generated/servicecatalog/v1beta1/serviceplan.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog.go
  pkg/registry/servicecatalog/serviceplan/storage.go
  pkg/registry/servicecatalog/serviceplan/strategy.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#1822 Enable verbose logging in svcat
  cmd/svcat/main.go
  cmd/svcat/plugin/plugin.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S, svcat
