Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-07, with the labels that each got.

#2146 Adding ServicePlan Control Loops
  pkg/controller/controller.go
  pkg/controller/controller_serviceplan.go
  pkg/controller/controller_serviceplan_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2159 Update bind loop support for namespaced classes and plans
  pkg/controller/controller.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_ns_test.go
  pkg/controller/controller_ns_test.go
  pkg/controller/controller_test.go
  pkg/pretty/pretty_names.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#2174 Add coverage for switch stmt case in parameters_test.go
  cmd/svcat/parameters/parameters_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/XS

#2160 Vet fixes
  pkg/controller/controller_binding.go
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2173 chmod +x repo-sync
  .travis.yml
  test/repo-sync.sh
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2103 send cluster ID as the organization GUID
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2182 golang 1.10
  .travis.yml
  Makefile
Labels: LGTM1, LGTM3, approved, cncf-cla: yes, lgtm, size/S

#2158 Enable passing a kubeconfig file to apiserver
  cmd/apiserver/app/server/options.go
  cmd/apiserver/app/server/util.go
  pkg/svcat/kube/kube.go
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/M

#2192 v0.1.24 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2194 Update rbac.yaml to conditionally create namespace scoped resource RBAC
  charts/catalog/templates/rbac.yaml
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, size/S

#2198 v0.1.25 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2153 Re-work TestCreateServiceInstanceWithProvisionFailure to mitigate its flake
  test/integration/controller_instance_test.go
  test/util/util.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, size/L

#2206 PR Template
  .github/PR_TEMPLATE.md
  CONTRIBUTING.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2205 Link to charter
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2186 lint ignores files marked as generated
  Makefile
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_update_references.go
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/serviceinstance_expansion.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, size/XS

#2204 Add deregister broker command to svcat
  cmd/svcat/broker/deregister_cmd.go
  cmd/svcat/broker/deregister_cmd_test.go
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2196 Export BrokerAuthSarCheck admission plugin name
  plugin/pkg/admission/broker/authsarcheck/admission.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2210 Adding docs for namespaced broker resources
  docs/README.md
  docs/namespaced-broker-resources.md
  docs/resources.md
  docsite/_config.yml
  docsite/_data/namespaced-broker-resources.yml
  docsite/_data/resources.yml
  docsite/index.html
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2213 v0.1.26 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2211 Introduce `spec.free` to catalog restrictions for Plans
  docs/README.md
  docs/catalog-restrictions.md
  docs/namespaced-broker-resources.md
  docsite/_config.yml
  docsite/_data/catalog-restrictions.yml
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/filter.go
  pkg/apis/servicecatalog/v1beta1/filter_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2219 update approvers
  OWNERS
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2220 Define common interfaces for cluster and namespaced classes and plans
  pkg/apis/servicecatalog/v1beta1/class.go
  pkg/apis/servicecatalog/v1beta1/plan.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/plan.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2222 Flip Chairs (╯°□°）╯︵ ┻━┻
  docsite/community.md
  docsite/images/arschles.jpg
  docsite/images/duglin.png
  docsite/images/pmorie.jpg
  docsite/images/vaikas-google.jpg
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/S

#2223 Adding jeremyrickard to OWNERS file
  OWNERS
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2179 Add unit test for cmd/svcat/broker/describe_cmd.go
  cmd/svcat/broker/describe_cmd_test.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2225 Extract containers resources to helm chart values
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/M

#2161 test storages to make sure they are appropriate types
  pkg/registry/servicecatalog/rest/rest_suite_test.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2065 delay between provisioning retries
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2116 Support ns-scoped resources in svcat get classes
  .gitignore
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/command/command.go
  cmd/svcat/command/scoped.go
  cmd/svcat/output/class.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/test/helper.go
  cmd/svcat/testdata/kubeconfig.tmpl.yaml
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/get-class.txt
  cmd/svcat/testdata/output/get-classes.json
  cmd/svcat/testdata/output/get-classes.txt
  cmd/svcat/testdata/output/get-classes.yaml
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses/4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses/f1a80068-e366-494e-92d6-a0782337945b.json
  cmd/svcat/testdata/responses/catalog/serviceclasses.json
  docs/cli.md
  pkg/apis/servicecatalog/v1beta1/class.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/scope.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XL

#2171 Make Svcat print help text if command is incorrect
  cmd/svcat/command/command.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2228 Update docs for counterfeiter
  docs/devguide.md
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2224 Refactor formatted interface to be consistent with the others
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/binding/get_cmd_test.go
  cmd/svcat/broker/describe_cmd_test.go
  cmd/svcat/broker/get_cmd.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/command/command.go
  cmd/svcat/command/formatted.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/output/binding.go
  cmd/svcat/output/broker.go
  cmd/svcat/output/class.go
  cmd/svcat/output/instance.go
  cmd/svcat/output/output.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/get_cmd.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2232 Source code warning for use of deprecated guid fields
  pkg/controller/controller_instance.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/S

#2234 Test svcat gracefully handles the ns-broker flag being disabled
  cmd/svcat/svcat_test.go
  pkg/svcat/service-catalog/class.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/M

#2235 Refactored `pkg/svcat/kube/kube.go` to `pkg/util/kube/kube.go`
  cmd/apiserver/app/server/util.go
  cmd/svcat/main.go
  pkg/util/kube/kube.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2231 repo-sync script fix
  test/repo-sync.sh
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2236 v0.1.27-release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2238 Fix describe broker test
  cmd/svcat/broker/describe_cmd_test.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2237 remove from travis integration-tests which are now running in prow
  .travis.yml
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2241 add mailing list to README
  README.md
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2240 Fix typo.
  docs/resources.md
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XS

#2230 Add ginkgo tests for svcat get classes
  cmd/svcat/class/get_cmd.go
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2190 Add svcat command to create user-defined cluster-scoped classes
  cmd/svcat/class/create_cmd.go
  cmd/svcat/class/create_cmd_test.go
  cmd/svcat/main.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/create-class.txt
  cmd/svcat/testdata/plugin.yaml
  docs/cli.md
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/L

#2245 Add jberkhahn to OWNERS files
  OWNERS
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/S

#2227 Include namespaced brokers in svcat get brokers
  cmd/svcat/broker/get_cmd.go
  cmd/svcat/broker/get_cmd_test.go
  cmd/svcat/output/broker.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/get-broker.txt
  cmd/svcat/testdata/output/get-brokers.json
  cmd/svcat/testdata/output/get-brokers.txt
  cmd/svcat/testdata/output/get-brokers.yaml
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebrokers.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebrokers/ups-broker.json
  contrib/examples/consumer/main.go
  docs/cli.md
  pkg/apis/servicecatalog/v1beta1/broker.go
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, lgtm, size/XL
