Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-06, with the labels that each got.

#2087 v0.1.21 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2080 Log the resourceVersion of the object we're processing
  pkg/controller/controller.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_servicebroker.go
  pkg/pretty/context_builder.go
  pkg/pretty/context_builder_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2072 Publish canary builds of the svcat cli
  contrib/travis/deploy.sh
  docs/install.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2069 Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2074 cache mounted into docker
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2094 Notify mailing list of master and release failures
  .travis.yml
  REVIEWING.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2077 e2e details and example
  docs/devguide.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2082 RenameKey transform shouldn't add a new key if the from key doesn't exist
  pkg/controller/controller_binding.go
  test/integration/controller_binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2098 doc: add details on quicker running of a specific integration test
  docs/devguide.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2078 Ensure finalizer is removed when 409 Conflict returned on status update
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, needs-rebase, size/M

#2099 mention /cc Prow command in user contribution docs
  docs/devguide.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2096 Verify builds on all platforms on master
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/XS

#2101 Allow lists in --param
  cmd/svcat/parameters/parameters.go
  cmd/svcat/parameters/parameters_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2090 Adds annotations to catalog chart
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2022 Namespaced ref support for ServiceInstance
  cmd/svcat/output/instance.go
  pkg/apis/servicecatalog/plan_reference.go
  pkg/apis/servicecatalog/plan_reference_test.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/plan_reference.go
  pkg/apis/servicecatalog/v1beta1/plan_reference_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_instance.go
  pkg/openapi/openapi_generated.go
  plugin/pkg/admission/serviceplan/changevalidator/admission.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission.go
  plugin/pkg/admission/serviceplan/defaultserviceplan/admission_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#2122 Fix Travis Config
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2121 Make readiness and liveliness probes optional
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2049 Fix unbind output
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/output/yaml_test.go
  cmd/svcat/svcat_test.go
  cmd/svcat/test/helper.go
  cmd/svcat/testdata/output/bind-instance-and-wait.txt
  cmd/svcat/testdata/output/bind-instance.txt
  cmd/svcat/testdata/output/delete-binding-and-wait.txt
  cmd/svcat/testdata/output/delete-binding.txt
  cmd/svcat/testdata/output/deprovision-instance-and-wait.txt
  cmd/svcat/testdata/output/deprovision-instance.txt
  cmd/svcat/testdata/output/provision-instance-and-wait.txt
  cmd/svcat/testdata/output/provision-instance.txt
  cmd/svcat/testdata/output/unbind-instance-and-wait.txt
  cmd/svcat/testdata/output/unbind-instance.txt
  pkg/svcat/service-catalog/binding.go
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/L

#2110 Update ServiceBinding's status when ServiceInstance has unresolved refs
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2123 Speed up travis build
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/M

#2115 Refactor Namespaced svcat commands
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/command/command.go
  cmd/svcat/command/namespaced.go
  cmd/svcat/command/waitable.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/describe_cmd.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/instance/touch_cmd.go
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/L

#2102 Split docs build into travis stage
  .travis.yml
  Makefile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2117 Remove unused function
  cmd/svcat/output/class.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2129 Adding some volunteers to the SECURITY_CONTACTS file.
  SECURITY_CONTACTS
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2137 Allow ns refs through ref update strategy
  pkg/registry/servicecatalog/instance/strategy.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2139 v0.1.22 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2126 Remove xbuild checks from main Travic CI job
  .travis.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/XS

#2135 Add issue template
  .github/ISSUE_TEMPLATE.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2095 Distinguish between user-defined and managed resources
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2130 Owners file updates
  OWNERS
  charts/healthcheck/OWNERS
  cmd/healthcheck/OWNERS
  cmd/svcat/OWNERS
  pkg/registry/OWNERS
  pkg/svcat/OWNERS
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2007 Add ServiceClass control loop
  pkg/controller/controller.go
  pkg/controller/controller_serviceclass.go
  pkg/controller/controller_serviceclass_test.go
Labels: LGTM1, cncf-cla: yes, size/L

#2040 svcat: Allow users to delete multiple bindings by using multiple --name flags
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/testdata/output/delete-binding-and-wait.txt
  cmd/svcat/testdata/output/unbind-instance-and-wait.txt
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2075 Add cmd unittest
  cmd/svcat/binding/describe_cmd_test.go
  cmd/svcat/binding/get_cmd_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2136 use common util for config loading
  test/e2e/framework/util.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2140 Add warning about json params
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, cncf-cla: yes, size/S

#2138 basic test of status types
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/clusterservicebroker/storage.go
  pkg/registry/servicecatalog/clusterserviceclass/storage.go
  pkg/registry/servicecatalog/clusterserviceplan/storage.go
  pkg/registry/servicecatalog/instance/storage.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
  pkg/registry/servicecatalog/servicebroker/storage.go
  pkg/registry/servicecatalog/serviceclass/storage.go
  pkg/registry/servicecatalog/serviceplan/storage.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2148 Add a nodeSelector to the chart
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2109 Fix svcat version command & add tests
  cmd/svcat/output/version.go
  cmd/svcat/versions/version_cmd.go
  cmd/svcat/versions/version_cmd_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2150 Fix bad merge
  cmd/svcat/binding/describe_cmd_test.go
  cmd/svcat/binding/get_cmd_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, lgtm, size/XS

#2125 reenable the controller default relist interval
  pkg/apis/servicecatalog/v1beta1/defaults.go
  pkg/apis/servicecatalog/v1beta1/defaults_test.go
  pkg/apis/servicecatalog/validation/broker.go
  pkg/apis/servicecatalog/validation/broker_test.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
Labels: LGTM1, cncf-cla: yes, size/M

#2155 ExternalID selectors for instances and bindings
  pkg/apis/servicecatalog/v1beta1/conversion.go
  pkg/apis/servicecatalog/v1beta1/conversion_test.go
  pkg/apis/servicecatalog/v1beta1/register.go
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/instance/storage.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2147 Use encrypted service account JSON for uploading chart
  .travis.yml
  contrib/travis/gcloud-key-file.json.enc
  test/repo-sync.sh
Labels: LGTM1, LGTM2, approved, cncf-cla: yes, size/S

#2133 Update instance loop support for namespaced classes and plans
  .gitignore
  pkg/apis/servicecatalog/plan_reference.go
  pkg/apis/servicecatalog/v1beta1/plan_reference.go
  pkg/controller/controller.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_ns_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XXL

#2089 Add plan/class filter options to svcat get instances
  cmd/svcat/command/classfiltered.go
  cmd/svcat/command/command.go
  cmd/svcat/command/planfiltered.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/get-instances-all-namespaces-by-class.txt
  cmd/svcat/testdata/output/get-instances-all-namespaces-by-plan.txt
  cmd/svcat/testdata/output/get-instances-all-namespaces-by-wrong-class.txt
  cmd/svcat/testdata/output/get-instances-all-namespaces-by-wrong-plan.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2154 use the built integration.test binary
  Makefile
  test/integration.sh
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2169 v0.1.23 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2172 Docker 17.05+ is required for dev builds
  docs/devguide.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS
