Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-10, with the labels that each got.

#2370 Fix the controller updateServiceBrokerClient method.
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2368 Handle polling errors and update status appropriately
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2377 Explain project roles and how to attain them
  REVIEWING.md
  docs/contribute/ladder.md
  docs/devguide.md
  docsite/_config.yml
  docsite/_data/ladder.yml
  docsite/community.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2378 SECURITY_CONTACTS, remove MHB, add jboyd01
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2376 Enable ginkgo cmd/svcat unit tests to run and fix existing ones
  cmd/svcat/class/class_suite_test.go
  cmd/svcat/class/create_cmd_test.go
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/plan/get_cmd_test.go
  cmd/svcat/plan/plan_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2355 Fix comments on 'get bindings'
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/testdata/plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2383 Update k8s dependencies
  Gopkg.lock
  Gopkg.toml
  pkg/openapi/openapi_generated.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/labels/selector.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1alpha1/generated.pb.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1beta1/generated.pb.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/apiserver/pkg/registry/rest/create.go
  vendor/k8s.io/apiserver/pkg/registry/rest/update.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/lease_manager.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/buffered/buffered.go
  vendor/k8s.io/apiserver/plugin/pkg/audit/truncate/truncate.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/transport/round_trippers.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2315 Make svcat sync broker command support namespace
  cmd/svcat/broker/sync_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/sync-broker-ns.txt
  cmd/svcat/testdata/output/sync-broker.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebrokers.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebrokers/ups-broker-ns.json
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2345 make register/deregister support namespaced brokers
  cmd/svcat/broker/deregister_cmd.go
  cmd/svcat/broker/deregister_cmd_test.go
  cmd/svcat/broker/register_cmd.go
  cmd/svcat/broker/register_cmd_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/apis/servicecatalog/v1beta1/broker.go
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2389 Bump to v0.1.35
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S

#2387 Bump dep version
  Gopkg.lock
  build/build-image/Dockerfile
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2395 typo fix about arguments
  cmd/svcat/broker/deregister_cmd.go
  cmd/svcat/broker/register_cmd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2391 minor fixes for svcat sync broker command
  cmd/svcat/class/create_cmd_test.go
  cmd/svcat/command/command.go
  cmd/svcat/command/scoped.go
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/broker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2392 Fix svcat create class
  cmd/svcat/class/create_cmd.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/create-cluster-class.txt
  cmd/svcat/testdata/output/create-namespace-class.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2399 No need for n3wscott to be in the review list.
  cmd/svcat/OWNERS
  pkg/svcat/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2400 Don't return ServiceInstance in resolveClusterReferences and related methods
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2398 Fix indent so minReadySeconds is under spec
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2403 Remove reduplication in contrib
  contrib/pkg/brokerapi/fake/fake.go
  contrib/pkg/brokerapi/service_plan.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2404 Fix documents issue
  docs/auth.md
  docs/devguide.md
  docs/v1/milestones.md
  docs/v1/use-cases.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2361 Add scoped/namespaced flags to describe plan
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/plan/describe_cmd_test.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/plan/get_cmd_test.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/describe-namespace-plan.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans/86064792-7ea2-467b-af93-ac9694d96d52.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_fieldSelector=spec.externalName=default.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_fieldSelector=spec.externalName=namespacedplan.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_fieldSelector=spec.externalName=premium.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_fieldSelector=spec.serviceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=namespacedplan.json
  pkg/apis/servicecatalog/v1beta1/plan.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/plan_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2406 Fix typos in the hack script comments
  pkg/kubernetes/hack/lib/golang.sh
  pkg/kubernetes/hack/lib/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2402 Replace expectXxx functions with asserts and wrap code with t.Run()
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_serviceclass_test.go
  pkg/controller/controller_serviceplan_test.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2416 move pmorie to chair emeritus, add jboyd01
  docsite/community.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2409 Add marketplace command to svcat
  cmd/svcat/extra/extra_suite_test.go
  cmd/svcat/extra/marketplace_cmd.go
  cmd/svcat/extra/marketplace_cmd_test.go
  cmd/svcat/main.go
  cmd/svcat/output/class.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2419 Check only relevant resource APIs via discovery client at the controller-manager startup
  cmd/controller-manager/app/controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2420 Bump release v 0.1.36
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2423 fix typo in class.go
  pkg/apis/servicecatalog/v1beta1/class.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2410 Show DefaultProvisionParameters for plans in svcat
  cmd/svcat/output/plan.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/testdata/output/describe-plan.txt
  cmd/svcat/testdata/output/get-plan.json
  cmd/svcat/testdata/output/get-plan.yaml
  cmd/svcat/testdata/responses/catalog/clusterserviceplans/86064792-7ea2-467b-af93-ac9694d96d52.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.externalName=default.json
  pkg/apis/servicecatalog/v1beta1/plan.go
  pkg/svcat/service-catalog/plan.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2417 Adjust validations to fit updated OSB API
  pkg/apis/servicecatalog/validation/binding.go
  pkg/apis/servicecatalog/validation/binding_test.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/validation/serviceclass.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/validation/serviceplan.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2405 Delete duplication in files
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/controller/controller_instance_test.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2430 Fix an error message problem
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm

#2388 Class default provision params
  docs/service-plan-defaults.md
  docsite/_data/service-plan-defaults.yml
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/unstructured_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/openapi/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2433 make svcat marketplace print plan external names
  cmd/svcat/extra/marketplace_cmd_test.go
  cmd/svcat/output/class.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2434 Fix default provision parameters checking comment problem
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2436 Bump version 0.1.37
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2401 update of outputs for walkthrough
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2440 Fix typo in Update test_context.go
  test/e2e/framework/test_context.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2443 Correct the returned messages in broker_client_manager_test.go
  pkg/controller/broker_client_manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2444 Fix typos
  docs/v1/user-story.md
  pkg/registry/servicecatalog/instance/strategy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2446 fix register cluster broker without auth info
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2447 fix typo
  contrib/examples/prometheus/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
