Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-12, with the labels that each got.

#2490 Add readiness probes and split checks from liveness probes
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
  cmd/apiserver/app/server/run_server.go
  cmd/controller-manager/app/controller_manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2516 Fix ups-broker install instructions
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2518 Fix name of errorDeprovisionCalledReason constant
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2520 Don't retry upon receiving 'failed' state in the last operation polling response
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2515 Fix missing quotation & Error string should not be capitalized or end with punctuation.
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2522 Fix copy/paste error in prepareBindRequest()
  pkg/controller/controller_binding.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2525 Print object JSON in event handlers
  pkg/controller/controller.go
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/S
