Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-05, with the labels that each got.

#2002 fix secret parameter example, add some details
  docs/parameters.md
Labels: LGTM1, LGTM2, size/M

#2014 v0.1.17 release updates
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2013 use all AdmissionControl plugins specified as enabled
  cmd/apiserver/app/server/util.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2003 scratch instead of debian
  Makefile
  build/service-catalog/Dockerfile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2018 re-enable Jenkins to run e2e
  Jenkinsfile
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2027 v0.1.18 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2024 Not all shells set PWD
  Makefile
Labels: cncf-cla: yes, size/XS

#1922 Ensure ServiceBinding gets deleted when ServiceInstance updated to an…
  pkg/controller/controller.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#1991 Add --wait flag to svcat commands
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/command/command.go
  cmd/svcat/command/waitable.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/secret.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2028 Set ExternalID in strategy, not defaults
  pkg/apis/servicecatalog/v1beta1/defaults.go
  pkg/apis/servicecatalog/v1beta1/defaults_test.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.defaults.go
  pkg/registry/servicecatalog/binding/strategy.go
  pkg/registry/servicecatalog/binding/strategy_test.go
  pkg/registry/servicecatalog/instance/strategy.go
  pkg/registry/servicecatalog/instance/strategy_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2026 don't list plans twice (svcat describe class --traverse)
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/broker/describe_cmd.go
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/instance/describe_cmd.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2038 Improve svcat's "x is required" error messages & make them consistent
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/broker/describe_cmd.go
  cmd/svcat/broker/sync_cmd.go
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/describe_cmd.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/svcat_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#1941 allow nill service plan during instance last op poll (#1940)
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2041 Improve devguide for first time contributors
  docs/devguide.md
  docsite/_data/devguide.yaml
  internal/test/test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2043 svcat: Show ParametersFrom in describe commands
  cmd/svcat/output/binding.go
  cmd/svcat/output/instance.go
  cmd/svcat/output/yaml.go
  cmd/svcat/testdata/output/describe-binding-show-secrets.txt
  cmd/svcat/testdata/output/describe-binding.txt
  cmd/svcat/testdata/output/describe-instance.txt
  cmd/svcat/testdata/output/get-binding.json
  cmd/svcat/testdata/output/get-binding.yaml
  cmd/svcat/testdata/output/get-instance.json
  cmd/svcat/testdata/output/get-instance.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebindings/ups-binding.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceinstances/ups-instance.json
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2048 v0.1.19 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2050 Add short description to svcat install and hide command in plugin mode
  cmd/svcat/main.go
  cmd/svcat/plugin/manifest.go
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2047 Fix svc-cat.io button links
  docsite/editdocs.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2045 Add make test-update-goldenfiles target
  Makefile
  docs/devguide.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/S

#2044 Ensure examples are included in svcat's plugin.yaml
  cmd/svcat/completion/completion_cmd.go
  cmd/svcat/plugin/manifest.go
  cmd/svcat/testdata/plugin.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2058 Add minimum required etcd version
  charts/catalog/README.md
  docs/install.md
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2042 cluster-info configmap role namespace issues
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS

#2056 Svcat help improvements
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/broker/describe_cmd.go
  cmd/svcat/broker/get_cmd.go
  cmd/svcat/broker/sync_cmd.go
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/command/command.go
  cmd/svcat/completion/completion_cmd.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/instance/describe_cmd.go
  cmd/svcat/instance/get_cmd.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/instance/touch_cmd.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/plugin/install.go
  cmd/svcat/plugin/manifest.go
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/versions/version_cmd.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2053 Add descriptive message for empty parameters when using svcat (#2051)
  cmd/svcat/output/yaml.go
  cmd/svcat/output/yaml_test.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/M

#2055 Tests for filter.go and comments in types.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/filter_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/openapi/openapi_generated.go
Labels: LGTM1, LGTM2, cncf-cla: yes, size/L

#2064 v0.1.20 Release
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2071 Bring back root CA certificates to a Service Catalog Docker image
  build/service-catalog/Dockerfile
Labels: LGTM1, cncf-cla: yes, size/S

#2083 fix docsite build issue
  build/docs.sh
  docsite/Gemfile
  docsite/Gemfile.lock
  docsite/_config.yml
Labels: LGTM1, LGTM2, cncf-cla: yes, size/XS
