Repository kubernetes-sigs/service-catalog, pull requests merged in 2018-09, with the labels that each got.

#2317 Rename PR_TEMPLATE.md to PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2297 Run validation subtests with testing.Run()
  pkg/apis/servicecatalog/validation/binding_test.go
  pkg/apis/servicecatalog/validation/broker_test.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/validation/serviceclass_test.go
  pkg/apis/servicecatalog/validation/serviceplan_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2314 Add deregister command in svcat
  cmd/svcat/broker/deregister_cmd.go
  cmd/svcat/broker/deregister_cmd_test.go
  cmd/svcat/main.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/deregister-broker.txt
  cmd/svcat/testdata/plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2320 modify the document format
  docs/catalog-restrictions.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2285 Add namespace flags to get plans
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/plan/get_cmd_test.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/get-namespaced-plans.json
  cmd/svcat/testdata/output/get-namespaced-plans.txt
  cmd/svcat/testdata/output/get-namespaced-plans.yaml
  cmd/svcat/testdata/output/get-plan.txt
  cmd/svcat/testdata/output/get-plans-by-class.txt
  cmd/svcat/testdata/output/get-plans.json
  cmd/svcat/testdata/output/get-plans.txt
  cmd/svcat/testdata/output/get-plans.yaml
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans.json
  cmd/svcat/testdata/responses/catalog/serviceplans.json
  pkg/apis/servicecatalog/v1beta1/plan.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/plan_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2293 svcat deprovision --wait doesn't work properly in some cases
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/svcat_test.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2313 Use controller's default brokerRelistInterval for namespaced brokers
  pkg/controller/controller.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2330 Make the building of our build image smarter per issue 2329
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2323 Improve unit tests for pkg/svcat instance wait functions
  pkg/svcat/service-catalog/instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2333 Configure exponential backoff policy for brokers
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2336 Allow filtering of ServiceInstances on serviceClassRef/servicePlanRef.name
  pkg/apis/servicecatalog/v1beta1/conversion.go
  pkg/apis/servicecatalog/v1beta1/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2318 Fix wait functionality in svcat register command
  cmd/svcat/broker/register_cmd.go
  cmd/svcat/broker/register_cmd_test.go
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2282 Define default provisioning params on plans
  Gopkg.lock
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
  charts/catalog/values.yaml
  contrib/hack/start-server.sh
  docs/README.md
  docs/feature-gates.md
  docs/service-plan-defaults.md
  docsite/_config.yml
  docsite/_data/service-plan-defaults.yml
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/unstructured_test.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/parameters.go
  pkg/controller/parameters_test.go
  pkg/features/features.go
  pkg/openapi/openapi_generated.go
  vendor/github.com/peterbourgon/mergemap/LICENSE
  vendor/github.com/peterbourgon/mergemap/mergemap.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2338 revendor to osb client library 0.0.11
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/pmorie/go-open-service-broker-client/v2/bind.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/deprovision_instance.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/get_binding.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/get_catalog.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_binding_last_operation.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/poll_last_operation.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/provision_instance.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/unbind.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/update_instance.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2339 bump version 0.1.32
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2340 Show hover link for all headers
  docsite/_includes/footer-scripts.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2343 Add eriknelson to OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2346 Fix image tagging when releases use a lightweight tag
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2269 Add svcat support for creating user-defined namespace scoped classes
  cmd/svcat/class/create_cmd.go
  cmd/svcat/class/create_cmd_test.go
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/output/class.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/create-class.txt
  cmd/svcat/testdata/output/create-cluster-class.txt
  cmd/svcat/testdata/output/create-namespace-class.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses_fieldSelector=spec.externalName=user-provided-namespaced-service.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses_fieldSelector=spec.externalName=user-provided-service.json
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2351 Fix some typos
  cmd/healthcheck/framework/healthcheck.go
  cmd/healthcheck/framework/http.go
  cmd/healthcheck/framework/metrics.go
  cmd/healthcheck/framework/options.go
  cmd/healthcheck/framework/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2347 Explain how to claim an issue
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2281 Add script to deploy local canary build to dev environment
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
  contrib/hack/deploy-local-canary.sh
  docs/devguide.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2360 Fix typo: paramters -> parameters
  docs/v1/use-cases.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2337 Share OSB client for ServiceBroker
  pkg/controller/broker_client_manager.go
  pkg/controller/broker_client_manager_test.go
  pkg/controller/controller.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_test.go
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2363 typo fix about overridden
  cmd/controller-manager/app/options/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2364 bump to 0.1.33
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2366 Fix goldenfile ouput
  Makefile
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/plan/get_cmd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2266 Deprecate storage-type flag
  charts/catalog/templates/apiserver-deployment.yaml
  cmd/apiserver/app/server/options.go
  cmd/apiserver/app/server/run_server.go
  cmd/apiserver/app/server/server.go
  cmd/service-catalog/server/apiserver.go
  contrib/hack/start-server.sh
  pkg/apiserver/etcd_config.go
  pkg/apiserver/util.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog.go
  pkg/registry/servicecatalog/rest/storage_servicecatalog_test.go
  pkg/registry/servicecatalog/server/options.go
  pkg/registry/servicecatalog/server/options_test.go
  pkg/registry/settings/rest/storage_settings.go
  test/integration/clientset_test.go
  test/integration/controller_test.go
  test/integration/framework.go
  test/integration/podpreset_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2365 Update minikube start docs
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, size/M
