Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-01, with the labels that each got.

#2536 Swap Doug for Jonathan as chair
  docsite/community.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2542 Follow constant convention for ErrorWithOriginatingIdentityReason
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2534 link to the final charter in kubernetes/community
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2544 Add ClusterIP as a valid apiserver.service.type option
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2531 Detect no-op status updates
  pkg/client/clientset_generated/clientset/typed/servicecatalog/v1beta1/fake/fake_update_references.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  test/fake/serviceinstances.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2519 Fix condition reason constants
  pkg/controller/controller_binding.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2526 Fix TestReconcileServiceInstanceDeleteBlockedByCredentials
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2506 Fix incorrect condition & event msg on retriable instance update failures
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2517 Escape '/' characters when creating k8s names for classes and plans
  pkg/controller/controller.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_ns_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_serviceclass_test.go
  pkg/controller/controller_serviceplan_test.go
  pkg/controller/controller_test.go
  test/integration/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2550 Allow setting `--operation-polling-maximum-backoff-duration`
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2556 Bump release v 0.1.40
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S
