Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-05, with the labels that each got.

#2617 Enable use of namespaced broker in healthchecker
  charts/healthcheck/README.md
  cmd/healthcheck/framework/healthcheck.go
  cmd/healthcheck/framework/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2614 make svcat get/describe plan work with namesapced resources
  cmd/svcat/output/plan.go
  cmd/svcat/plan/describe_cmd.go
  cmd/svcat/plan/describe_cmd_test.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/plan/get_cmd_test.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2615 Make svcat broker commands with --wait support namespaced brokers
  cmd/svcat/broker/register_cmd.go
  cmd/svcat/broker/register_cmd_test.go
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2589 Add --abandon and --yes flags to svcat deprovision command
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/instance/deprovision_cmd.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/controller/controller.go
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2618 Make svcat provision support namespaced resources
  cmd/svcat/instance/instance_suite_test.go
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/instance/provision_cmd_test.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/provision-instance.txt
  cmd/svcat/testdata/plugin.yaml
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_fieldSelector=spec.serviceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceclasses_fieldSelector=spec.externalName=user-provided-service.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceplans_fieldSelector=spec.clusterServiceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceplans_fieldSelector=spec.serviceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468,spec.externalName=default.json
  pkg/apis/servicecatalog/v1beta1/class.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2620 Clean docs 2
  docs/install.md
  docs/tasks/index.md
  docs/tasks/stuck_instance.md
  docsite/_data/tasks.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2623 update sig chairs
  docsite/community.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2624 Bump version 0.2.0
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
  docs/feature-gates.md
  docs/namespaced-broker-resources.md
Labels: cncf-cla: yes, lgtm, size/M

#2628 Fix the missing flag in the instance tests from the svcat package
  cmd/svcat/instance/provision_cmd_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#2631 pass correct scope when finding plan k8s name in svcat provision
  cmd/svcat/instance/provision_cmd.go
  cmd/svcat/instance/provision_cmd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2641 Update OWNERS files
  SECURITY_CONTACTS
  charts/healthcheck/OWNERS
  cmd/healthcheck/OWNERS
  cmd/svcat/OWNERS
  pkg/svcat/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#2629 Move closing stream after error handling, add container name in e2e scenario
  test/e2e/walkthrough.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS
