Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-09, with the labels that each got.

#2689 Bump OSB client lib
  Gopkg.lock
  Gopkg.toml
  pkg/controller/case_test.go
  test/integration/controller_test.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/errors.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2667 Add controller Service Instance test
  pkg/controller/case_test.go
  pkg/controller/controller_flow_binding_test.go
  pkg/controller/controller_flow_instance_test.go
  pkg/controller/controller_flow_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#2699 bump chart versions to 0.2.2
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S

#2702 change pmorie lib import to kubernetes-sigs location
  Gopkg.lock
  Gopkg.toml
  cmd/controller-manager/app/options/options.go
  contrib/pkg/README.md
  pkg/controller/broker_client_manager.go
  pkg/controller/broker_client_manager_test.go
  pkg/controller/case_test.go
  pkg/controller/controller.go
  pkg/controller/controller_actions_test.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_ns_test.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_flow_binding_test.go
  pkg/controller/controller_flow_instance_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_test.go
  pkg/controller/originating_identity.go
  pkg/controller/originating_identity_test.go
  pkg/metrics/osbclientproxy/osbproxy.go
  test/integration/controller_binding_test.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
  test/integration/filtered_services_and_plans_test.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/LICENSE
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/bind.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/client.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/constants.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/deprovision_instance.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/doc.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/errors.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/fake/fake.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/generator/catalog.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/generator/generator.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/generator/got.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/generator/types.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/generator/uuid.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/get_binding.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/get_catalog.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/interface.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/poll_binding_last_operation.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/poll_last_operation.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/provision_instance.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/types.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/unbind.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/update_instance.go
  vendor/github.com/kubernetes-sigs/go-open-service-broker-client/v2/version.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/doc.go
  vendor/github.com/pmorie/go-open-service-broker-client/v2/generator/uuid.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2703 State in the documetation that svc-cat depends on k8s v1.13+
  charts/catalog/README.md
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2708 Change controller manager deployment charts template
  charts/catalog/templates/controller-manager-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2714 Update regex to allow "-beta.X" releases
  contrib/hack/ci/publish-release.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2715 Bump Service Catalog release to 0.3.0-beta.0
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S
