Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-06, with the labels that each got.

#2642 remove obsolete documentation on proposed future v1
  CONTRIBUTING.md
  docs/README.md
  docs/v1/README.md
  docs/v1/api-server-walkthrough.md
  docs/v1/api.md
  docs/v1/milestones.md
  docs/v1/simple-service-broker-writing.md
  docs/v1/use-cases.md
  docs/v1/user-story.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2645 Bump debian-base images version to v1.0.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2627 Fix the test-broker flags parsing
  contrib/cmd/test-broker/test-broker.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#2644 bump v0.2.1
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, lgtm, size/S

#2656 Fix deprovisioning process in TestBroker
  contrib/pkg/broker/test_broker/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2655 update OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2664 change controller finalizer back to kubernetes-incubator
  cmd/svcat/testdata/output/get-binding.json
  cmd/svcat/testdata/output/get-binding.yaml
  cmd/svcat/testdata/output/get-bindings.json
  cmd/svcat/testdata/output/get-bindings.yaml
  cmd/svcat/testdata/output/get-broker.json
  cmd/svcat/testdata/output/get-broker.yaml
  cmd/svcat/testdata/output/get-brokers.json
  cmd/svcat/testdata/output/get-brokers.yaml
  cmd/svcat/testdata/output/get-instance.json
  cmd/svcat/testdata/output/get-instance.yaml
  cmd/svcat/testdata/output/get-instances.json
  cmd/svcat/testdata/output/get-instances.yaml
  cmd/svcat/testdata/responses/catalog/clusterservicebrokers.json
  cmd/svcat/testdata/responses/catalog/clusterservicebrokers/ups-broker.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebindings.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebindings/ups-binding.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebrokers.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/servicebrokers/ups-broker.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceinstances.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceinstances/ups-instance.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebindings.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebindings/ups-binding.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebrokers.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/servicebrokers/ups-broker-ns.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceinstances.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceinstances/ups-instance.json
  cmd/svcat/testdata/responses/catalog/servicebindings.json
  cmd/svcat/testdata/responses/catalog/serviceinstances.json
  cmd/svcat/testdata/responses/catalog/serviceinstances_fieldSelector=spec.clusterServicePlanRef.name=86064792-7ea2-467b-af93-ac9694d96d52.json
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2640 Take advertise client urls from configuration
  charts/catalog/templates/apiserver-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2596 New controller tests - deletion resources
  .gitignore
  Makefile
  pkg/controller/case_test.go
  pkg/controller/controller_flow_binding_test.go
  pkg/controller/controller_flow_instance_test.go
  pkg/controller/controller_flow_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL
