Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-10, with the labels that each got.

#2719 Add CRD waiter for migration job and webhook server
  charts/catalog/templates/migration-job.yaml
  cmd/controller-manager/app/controller_manager.go
  cmd/migration/migration.go
  cmd/webhook/server/webhook.go
  pkg/migration/migration.go
  pkg/util/crd_waiter.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2717 Improve CRD liveness/readiness probe
  charts/catalog/templates/crds/clusterservicebroker.yaml
  charts/catalog/templates/crds/clusterserviceclass.yaml
  charts/catalog/templates/crds/clusterserviceplan.yaml
  charts/catalog/templates/crds/servicebinding.yaml
  charts/catalog/templates/crds/servicebroker.yaml
  charts/catalog/templates/crds/serviceclass.yaml
  charts/catalog/templates/crds/serviceinstance.yaml
  charts/catalog/templates/crds/serviceplan.yaml
  cmd/controller-manager/app/controller_manager.go
  cmd/webhook/server/webhook.go
  pkg/probe/crd_probe.go
  pkg/probe/crd_probe_test.go
  pkg/util/crd_waiter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2721 Add support for imagePullSecrets to helm charts
  charts/catalog/README.md
  charts/catalog/templates/cleaner-job.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/migration-job.yaml
  charts/catalog/templates/pre-migration-job.yaml
  charts/catalog/templates/webhook-deployment.yaml
  charts/catalog/values.yaml
  charts/healthcheck/templates/healthcheck-deployment.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/README.md
  charts/test-broker/templates/broker-deployment.yaml
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/templates/broker-deployment.yaml
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2722 Bump Service Catalog release to 0.3.0-beta.1
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S

#2727 Split the Service Catalog release job by arch type
  .travis.yml
  contrib/hack/ci/publish-svc-cat-release.sh
  contrib/hack/ci/publish-svcat-cli-release.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#2723 Dump cluster-info in case of failed migration and e2e tests
  contrib/hack/ci/lib/utilities.sh
  contrib/hack/ci/run-e2e-tests.sh
  contrib/hack/ci/run-migration-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2728 Change Deployment api to apps/v1
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/test-broker/templates/broker-deployment.yaml
  charts/ups-broker/templates/broker-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2731 Improve travis build - skip redundant jobs
  .travis.yml
  contrib/hack/ci/publish-svc-cat.sh
  contrib/hack/ci/publish-svcat-cli.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2729 cleanup codebase and run gofmt
  contrib/pkg/broker/server/server_test.go
  pkg/cleaner/cleaner_test.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_test.go
  test/integration/controller_binding_test.go
  test/integration/controller_instance_test.go
  test/integration/filtered_services_and_plans_test.go
  test/integration/framework.go
  test/upgrade/examiner/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2735 Fix ServiceInstance restore process in migration job
  pkg/migration/migration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2737 fix golint errors
  test/upgrade/examiner/internal/readiness/readiness.go
  test/upgrade/examiner/internal/readiness/sc_config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
