Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-08, with the labels that each got.

#2682 bump golang 1.12
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2690 Add option to execute e2e test both locally and CI
  .travis.yml
  Makefile
  contrib/hack/ci/assets/gcloud-key-file.json.enc
  contrib/hack/ci/assets/tiller-rbac.yaml
  contrib/hack/ci/lib/deps_ver.sh
  contrib/hack/ci/lib/utilities.sh
  contrib/hack/ci/publish-helm-chart.sh
  contrib/hack/ci/publish-release.sh
  contrib/hack/ci/run-e2e-tests.sh
  contrib/hack/create_artifacts.sh
  contrib/jenkins/build.sh
  contrib/jenkins/cleanup_cluster.sh
  contrib/jenkins/init_build.sh
  contrib/jenkins/init_cluster.sh
  contrib/jenkins/install_catalog.sh
  contrib/jenkins/run_e2e.sh
  contrib/jenkins/setup-sc-context.sh
  contrib/jenkins/test_walkthrough.sh
  docs/devguide.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2692 Update build scripts (v0.2)
  Makefile
  charts/catalog-v0.2/Chart.yaml
  charts/catalog-v0.2/README.md
  charts/catalog-v0.2/templates/_helpers.tpl
  charts/catalog-v0.2/templates/apiregistration.yaml
  charts/catalog-v0.2/templates/apiserver-deployment.yaml
  charts/catalog-v0.2/templates/apiserver-service.yaml
  charts/catalog-v0.2/templates/controller-manager-deployment.yaml
  charts/catalog-v0.2/templates/controller-manager-service.yaml
  charts/catalog-v0.2/templates/etcd-pvc.yaml
  charts/catalog-v0.2/templates/rbac.yaml
  charts/catalog-v0.2/templates/serviceaccounts.yaml
  charts/catalog-v0.2/values.yaml
  contrib/examples/prometheus/README.md
  contrib/hack/ci/assets/gcloud-key-file.json.enc
  contrib/hack/ci/publish-helm-chart.sh
  contrib/hack/ci/publish-release.sh
  contrib/hack/ci/run-e2e-tests.sh
  contrib/hack/deploy-local-canary.sh
  docs/devguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2693 Update documentation of v0.2 installation
  docs/design.md
  docs/devguide.md
  docs/install.md
  docs/resources.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
