Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-03, with the labels that each got.

#2565 Update concepts.yml
  docsite/_data/concepts.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2570 bump version 0.1.42
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2571 Add securityContext
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2574 reposition left menu (docs ToC) & make sure it doesn't overlap with other components
  docsite/js/script.js
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2575 Revert css overflow setting
  docsite/js/script.js
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2573 bump go 1.11.5
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2572 Update OWNERS and SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#2577 Improve caching OSB clients
  cmd/controller-manager/app/controller_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_test.go
  test/integration/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2581 Increase apiserver resource requests and limits
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2564 make svcat describe and get broker now support namespaced resources
  cmd/svcat/broker/describe_cmd.go
  cmd/svcat/broker/describe_cmd_test.go
  cmd/svcat/broker/get_cmd.go
  cmd/svcat/broker/get_cmd_test.go
  cmd/svcat/output/broker.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/output/describe-broker.txt
  cmd/svcat/testdata/output/register-broker.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2583 Update video links in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2585 Remove eriknelson from OWNERS file
  cmd/svcat/OWNERS
  pkg/registry/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2579 Add svcat unbind --abandon command
  cmd/svcat/binding/unbind_cmd.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
