Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-11, with the labels that each got.

#2741 Changing Class and Plans labels to sha224
  charts/catalog/templates/crds/serviceplan.yaml
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/responses/catalog/clusterserviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=0808f64e60d58979fcb676c96ec938270dea42445aeefcd3a4e6f8db.json
  cmd/svcat/testdata/responses/catalog/clusterserviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=730d36fa34c1b3308cbf85856900e29eac970fdb23febe2c193c4ea5.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_labelSelector=servicecatalog.k8s.io_spec.clusterServiceClassRef.name=e4e02e7aedb3d750ea411ce07935bf20814fbd4e89f2f98ca21aa1be,servicecatalog.k8s.io_spec.externalName=f0e8b3c2dda2512b55e4dc5d4859b1877e98109c7c4e755ccd2a5763.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_labelSelector=servicecatalog.k8s.io_spec.clusterServiceClassRef.name=e4e02e7aedb3d750ea411ce07935bf20814fbd4e89f2f98ca21aa1be.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=f0e8b3c2dda2512b55e4dc5d4859b1877e98109c7c4e755ccd2a5763,servicecatalog.k8s.io_spec.serviceClassRef.name=4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=f0e8b3c2dda2512b55e4dc5d4859b1877e98109c7c4e755ccd2a5763.json
  cmd/svcat/testdata/responses/catalog/clusterserviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=fe5831d8717bd462c29706065409c50624e5add9767bb9aee82e31f6.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=0808f64e60d58979fcb676c96ec938270dea42445aeefcd3a4e6f8db.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=730d36fa34c1b3308cbf85856900e29eac970fdb23febe2c193c4ea5.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=aad43c907292278117a32caa95fa8a7ce6b49575d6f7cfd8505d11bd.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=ade4172c49b5fb601b1752bd8f9663ad161735beb73ec2d3f274be89,servicecatalog.k8s.io_spec.serviceClassRef.name=e4e02e7aedb3d750ea411ce07935bf20814fbd4e89f2f98ca21aa1be.json
  cmd/svcat/testdata/responses/catalog/namespaces/default/serviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=ade4172c49b5fb601b1752bd8f9663ad161735beb73ec2d3f274be89.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=730d36fa34c1b3308cbf85856900e29eac970fdb23febe2c193c4ea5.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceplans_labelSelector=servicecatalog.k8s.io_spec.clusterServiceClassRef.name=e4e02e7aedb3d750ea411ce07935bf20814fbd4e89f2f98ca21aa1be,servicecatalog.k8s.io_spec.externalName=f0e8b3c2dda2512b55e4dc5d4859b1877e98109c7c4e755ccd2a5763.json
  cmd/svcat/testdata/responses/catalog/namespaces/test-ns/serviceplans_labelSelector=servicecatalog.k8s.io_spec.externalName=f0e8b3c2dda2512b55e4dc5d4859b1877e98109c7c4e755ccd2a5763,servicecatalog.k8s.io_spec.serviceClassRef.name=e4e02e7aedb3d750ea411ce07935bf20814fbd4e89f2f98ca21aa1be.json
  cmd/svcat/testdata/responses/catalog/serviceclasses_labelSelector=servicecatalog.k8s.io_spec.externalName=0808f64e60d58979fcb676c96ec938270dea42445aeefcd3a4e6f8db.json
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_clusterserviceclass.go
  pkg/controller/controller_clusterserviceclass_test.go
  pkg/controller/controller_clusterserviceplan.go
  pkg/controller/controller_clusterserviceplan_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_ns_test.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_ns_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_serviceclass.go
  pkg/controller/controller_serviceclass_test.go
  pkg/controller/controller_serviceplan.go
  pkg/controller/controller_serviceplan_test.go
  pkg/controller/controller_test.go
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/plan.go
  pkg/svcat/service-catalog/plan_test.go
  pkg/util/sha_generator.go
  pkg/webhook/servicecatalog/clusterserviceclass/mutation/handler.go
  pkg/webhook/servicecatalog/clusterserviceclass/mutation/handler_test.go
  pkg/webhook/servicecatalog/clusterserviceplan/mutation/handler.go
  pkg/webhook/servicecatalog/clusterserviceplan/mutation/handler_test.go
  pkg/webhook/servicecatalog/serviceclass/mutation/handler.go
  pkg/webhook/servicecatalog/serviceclass/mutation/handler_test.go
  pkg/webhook/servicecatalog/serviceinstance/mutation/default_service_plan.go
  pkg/webhook/servicecatalog/serviceinstance/mutation/default_service_plan_test.go
  pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go
  pkg/webhook/servicecatalog/serviceplan/mutation/handler.go
  pkg/webhook/servicecatalog/serviceplan/mutation/handler_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2733 Node selector is a dict
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/webhook-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2744 Bump Service Catalog release to 0.3.0-beta.2
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, size/S

#2748 Bump Service Catalog release to 0.3.0-beta.2 in Helm Charts
  charts/catalog/Chart.yaml
  charts/healthcheck/Chart.yaml
  charts/test-broker/Chart.yaml
  charts/ups-broker/Chart.yaml
Labels: approved, size/XS

#2749 fix: make allErrs complete in validateServiceClassSpec
  pkg/apis/servicecatalog/validation/serviceclass.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2750 init flags before parsing in e2e tests
  .travis.yml
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2711 Cascading binding deletion
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
  charts/catalog/values.yaml
  docs/feature-gates.md
  pkg/controller/case_test.go
  pkg/controller/controller_flow_instance_test.go
  pkg/controller/controller_instance.go
  pkg/features/features.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2743 Create sanity check script for migration
  contrib/hack/migration-check.sh
  docs/migration-apiserver-to-crds.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2753 Change Deployment api to apps/v1 in cleaner
  charts/catalog/templates/cleaner-job.yaml
  charts/catalog/templates/migration-job.yaml
  charts/catalog/templates/pre-migration-job.yaml
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
  test/upgrade/examiner/internal/readiness/readiness.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
