Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-02, with the labels that each got.

#2557 Check access to secrets from namespaced brokers
  plugin/pkg/admission/broker/authsarcheck/admission.go
  plugin/pkg/admission/broker/authsarcheck/admission_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2561 Fix OpenAPI checker violations
  cmd/healthcheck/framework/healthcheck.go
  cmd/svcat/binding/unbind_cmd_test.go
  cmd/svcat/output/binding.go
  contrib/build/violation_exceptions.txt
  pkg/apis/servicecatalog/testing/fuzzer.go
  pkg/apis/servicecatalog/types.go
  pkg/apis/servicecatalog/unstructured_test.go
  pkg/apis/servicecatalog/v1beta1/plan.go
  pkg/apis/servicecatalog/v1beta1/types.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.conversion.go
  pkg/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/apis/servicecatalog/validation/binding.go
  pkg/apis/servicecatalog/validation/binding_test.go
  pkg/apis/servicecatalog/validation/instance.go
  pkg/apis/servicecatalog/validation/instance_test.go
  pkg/apis/servicecatalog/zz_generated.deepcopy.go
  pkg/controller/controller.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_ns_test.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/binding/strategy_test.go
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/binding_test.go
  pkg/svcat/service-catalog/instance.go
  pkg/svcat/service-catalog/instance_test.go
  plugin/pkg/admission/servicebindings/lifecycle/admission.go
  plugin/pkg/admission/servicebindings/lifecycle/admission_test.go
  test/e2e/walkthrough.go
  test/integration/clientset_test.go
  test/integration/controller_binding_test.go
  test/integration/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2562 Use TRAVIS_TAG for svcat version when publishing
  contrib/travis/deploy.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2493 Initialize ClusterServiceBroker/ServiceBroker client only on add/update actions
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_ns_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_servicebroker_test.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2546 Simplify compact code.
  pkg/controller/controller_binding.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2566 Bump version 0.1.41
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2567 Init klog flags in ups-broker and test-broker
  contrib/cmd/test-broker/test-broker.go
  contrib/cmd/user-broker/user-broker.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2568 Remove @nilebox from the list of OWNERS of Service Catalog
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
