Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-04, with the labels that each got.

#2547 channel neither has values in nor be closed .
  cmd/apiserver/app/server/run_server.go
  pkg/hyperkube/hyperkube_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2595 Fix serviceclass to serviceclasses
  pkg/controller/controller_clusterservicebroker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2600 Remove badge for unused Jenkins build
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2591 Fix RemoveFinalizerForBindings and RemoveBindingFinalizerByInstance tests
  pkg/svcat/service-catalog/binding_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2587 Add Tasks section to docs
  docs/tasks/index.md
  docs/tasks/install_broker.md
  docs/tasks/sync_broker.md
  docsite/_config.yml
  docsite/_data/tasks.yml
  docsite/_layouts/docsportal.html
  docsite/_layouts/docwithnav.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#2601 Fix the comments of the Name & Fix the msg of the etcd checker.
  cmd/apiserver/app/server/run_server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2598 Add namespaced e2e tests
  Makefile
  cmd/healthcheck/framework/healthcheck.go
  test/e2e/broker.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/test_context.go
  test/e2e/util.go
  test/e2e/walkthrough.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
  test/integration/deleted_services_and_plans_test.go
  test/integration/filtered_services_and_plans_test.go
  test/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2607 update jekyll & ffi to address CVE-2018-17567 & CVE-2018-1000201
  docsite/Gemfile
  docsite/Gemfile.lock
Labels: approved, cncf-cla: yes, lgtm, size/M

#2608 Use 2 resources instead of a list
  charts/catalog/templates/serviceaccounts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2606 add default values for apiVersion to be able to use helm template
  charts/catalog/templates/_helpers.tpl
  charts/catalog/templates/apiregistration.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2611 Fix the comments of the binding cmd.
  cmd/svcat/binding/bind_cmd.go
  cmd/svcat/binding/describe_cmd.go
  cmd/svcat/binding/get_cmd.go
  cmd/svcat/binding/unbind_cmd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2582 svcat describe and get classes now support namespaced resources
  cmd/svcat/class/describe_cmd.go
  cmd/svcat/class/describe_cmd_test.go
  cmd/svcat/class/get_cmd.go
  cmd/svcat/class/get_cmd_test.go
  cmd/svcat/output/plan.go
  cmd/svcat/plan/get_cmd.go
  cmd/svcat/svcat_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  pkg/svcat/service-catalog/class.go
  pkg/svcat/service-catalog/class_test.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2609 Add rbacApiVersion and use separate resources instead of a list
  charts/catalog/templates/_helpers.tpl
  charts/catalog/templates/rbac.yaml
  charts/catalog/values.yaml
  charts/healthcheck/templates/_helpers.tpl
  charts/healthcheck/templates/rbac.yaml
  charts/healthcheck/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2612 Bump release version 0.1.43
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: cncf-cla: yes, size/S

#2431 Add service resource for the controller manager
  charts/catalog/README.md
  charts/catalog/templates/controller-manager-service.yaml
  charts/catalog/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
