Repository kubernetes-sigs/service-catalog, pull requests merged in 2019-07, with the labels that each got.

#2668 Send 'previous_values' field in update service instance request body
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2671 Changed walkthrough from UPS to mini
  contrib/examples/walkthrough/mini-binding.yaml
  contrib/examples/walkthrough/mini-instance.yaml
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2669 Pass service instance name via ProvisionRequest context
  pkg/controller/controller_binding.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2665 Add missing line to copy the svcat.exe into bin folder
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2666 Make timeout of any request to the broker globally configurable
  charts/catalog/README.md
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
  cmd/controller-manager/app/controller_manager.go
  cmd/controller-manager/app/options/options.go
  pkg/apis/componentconfig/types.go
  pkg/controller/case_test.go
  pkg/controller/controller.go
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_clusterservicebroker_test.go
  pkg/controller/controller_servicebroker.go
  pkg/controller/controller_test.go
  test/integration/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
