Repository kubernetes-sigs/service-catalog, pull requests merged in 2020-07, with the labels that each got.

#2823 Fix RemoveFinalizer methods in svcat cli
  pkg/svcat/service-catalog/binding.go
  pkg/svcat/service-catalog/instance.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#2829 Update feature-gates.md
  docs/feature-gates.md
  docs/install.md
  docs/proposals/crd-implementation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2830 Remove Secret listener from controller
  charts/catalog/templates/rbac.yaml
  cmd/controller-manager/app/controller_manager.go
  pkg/controller/case_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
