Repository kubernetes-sigs/service-catalog, pull requests merged in 2020-03, with the labels that each got.

#2781 Do not build binaries for test-unit
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2777 change meetings to biweekly
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2764 Adding helm3 command
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2780 Update devguide.md
  docs/devguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2788 Fix `make verify`
  Makefile
  pkg/kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2790 Update ups-broker docs link to point to chart on github.
  docs/cli.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
