Repository kubernetes-sigs/service-catalog, pull requests merged in 2020-01, with the labels that each got.

#2754 Fixing error when plan is updated and mutateOnUpdate deletes ClusterServicePlanRef value
  pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2767 update coding-conventions.md
  docs/code-standards.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2768 remove underline before data
  docsite/_includes/templates/glossary/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2771 add a trigger for false status ServiceBinding at the end of SI reconc…
  pkg/controller/case_test.go
  pkg/controller/controller_binding.go
  pkg/controller/controller_instance.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2776 fix broken links:https://github.com/kubernetes/community/blob/master/…
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
