Repository kubernetes-sigs/service-catalog, pull requests merged in 2020-05, with the labels that each got.

#2794 Bump bundler version for jekyll and set fix version for jekyll
  build/docs.sh
  docsite/Gemfile.lock
Labels: approved, cncf-cla: yes, lgtm, size/M

#2797 Fix ServicePlan resync
  pkg/controller/controller_serviceplan.go
  pkg/controller/controller_serviceplan_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#2806 Update version from 0.2.2 to 0.2.3
  charts/catalog-v0.2/Chart.yaml
  charts/catalog-v0.2/README.md
  charts/catalog-v0.2/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S

#2803 Add option to specify k8s version
  contrib/hack/ci/lib/deps_ver.sh
  contrib/hack/ci/lib/utilities.sh
  contrib/hack/ci/run-e2e-tests.sh
  contrib/hack/ci/run-migration-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2808 Update dev guide to not refer to GOPATH in setup
  docs/devguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2811 Update version from 0.3.0-beta.2 to 0.3.0
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/values.yaml
  charts/healthcheck/Chart.yaml
  charts/healthcheck/values.yaml
  charts/test-broker/Chart.yaml
  charts/test-broker/README.md
  charts/test-broker/values.yaml
  charts/ups-broker/Chart.yaml
  charts/ups-broker/README.md
  charts/ups-broker/values.yaml
Labels: approved, cncf-cla: yes, size/S

#2812 Update mariadb version in walkthrough
  contrib/examples/walkthrough/mini-instance.yaml
  docs/walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/M
