Repository kubernetes-sigs/service-catalog, pull requests merged in 2021-01, with the labels that each got.

#2874 change helm repo installation instructions to GH pages location
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2873 Add namespace to service broker metrics
  pkg/controller/controller_clusterservicebroker.go
  pkg/controller/controller_servicebroker.go
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2870 Add install instruction to create the namespace
  docs/install.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2867 Make the metrics port configurable
  cmd/webhook/server/options.go
  cmd/webhook/server/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
